---
title: "portsmouth-darek-mdxbrain"
output:
  html_document:
    toc: yes
    df_print: paged

date: "_Last draft: `r format(Sys.time(), '%d %B, %Y %H:%M:%S')`_"
description: "mdx mice analysis"

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', format(Sys.time(), "%Y-%m-%d_%H-%M"), '.html'
      ),
      knit_root_dir = xfun::proj_root(),
      envir = globalenv()
    )
  })
---


```{r load_libraries, include=FALSE}
library(tidyverse)
library(preprocessCore)
library(future.apply)
library(rstatix)
library(RColorBrewer)
library(tictoc)
library(sva)
library(knitr)

source('analysis/utils.R')
anova_rds_path <- 'data/mdx_3way_anova_010.RDS'
sample_info_rds_path <- 'data/sample_info.RDS'
posthoc_rds_path <- 'data/posthoc_genotype.RDS'
```

```{r}
sview <- function(x) {
  x %>%
    select(-gene_stable_id, -gene_description, -chr, -gene_type, -gene_synonym) %>%
    select(-genotype:-`genotype:age_days:tissue`) %>%
    select(-starts_with('sample_'))
}
```

```{r}
compute_posthoc <- function(df, id_col, comp_fct, sample_info, p_adj_method = 'bonferroni') {
  # sample_info colnames must follow the convention: id, factor1, ..., factorn
  stopifnot(!duplicated(mdx_anova[[id_col]]))

  # rename columns to avoid future collisions
  sample_info <-
    sample_info %>%
    rename_with(function(x) paste0(x, '_fct'), -id)
  comp_fct <- paste0(comp_fct, '_fct')

  sample_factors <- colnames(sample_info)
  sample_factors <-
    sample_factors[!sample_factors %in% c('id', comp_fct)]

  df %>%
    pivot_longer(all_of(sample_info$id), names_to = 'group', values_to = 'value') %>%
    left_join(sample_info, by = c('group' = 'id')) %>%
    rename(comp_fct = {{ comp_fct }}) %>%
    group_by(across(all_of(c(id_col, sample_factors)))) %>%
    pairwise_t_test(
        value ~ comp_fct,
        pool.sd = FALSE,
        var.equal = TRUE
    ) %>%
    group_by(.data[[id_col]]) %>%
    mutate(p.adj = p.adjust(p, method = p_adj_method)) %>%
    select(-p.adj.signif)
}
```

```{r}
compute_folds <- function(df, id_col, sample_info, pairs) {
  stopifnot(!duplicated(mdx_anova[[id_col]]))

  sample_info <-
    sample_info %>%
    rename_with(function(x) paste0(x, '_fct'), -id)

  df_means <-
    df %>%
    pivot_longer(all_of(sample_info$id), names_to = 'group', values_to = 'value') %>%
    left_join(sample_info, by = c('group' = 'id')) %>%
    group_by(.data[[id_col]], genotype_fct, age_days_fct, tissue_fct) %>%
    summarise(mean_ = mean(value), .groups = 'drop') %>%
    pivot_wider(names_from = ends_with('_fct'), values_from = mean_)

  pairs_name <- names(pairs)
  for (i in 1:length(pairs)) {
    if (is.null(pairs_name)) {
      pair <- pairs[i]
    } else {
      pair <- pairs_name[i]
    }
    split_pair <- str_split(pairs[i], '\\W?-\\W?')[[1]]
    df_means <-
      df_means %>%
      mutate('{pair}' := .data[[split_pair[1]]] - .data[[split_pair[2]]])
  }
  df_means
}

```

```{r}
mdx_anova <- readRDS(anova_rds_path)
sample_info <- readRDS(sample_info_rds_path)

g_th <- 0.1
mdx_anova_filtered <-
  mdx_anova %>%
  filter(
    apply(select(., matches('.*genotype.*_fdr$')), 1, min) < g_th
  )
```

```{r filter_genotype_factors}
compute_posthoc <- function(df, id_col, comp_fct, sample_info, p_adj_method = 'bonferroni') {
  # sample_info colnames must follow the convention: id, factor1, ..., factorn
  stopifnot(!duplicated(mdx_anova[[id_col]]))

  # rename columns to avoid future collisions
  sample_info <-
    sample_info %>%
    rename_with(function(x) paste0(x, '_fct'), -id)
  comp_fct <- paste0(comp_fct, '_fct')

  sample_factors <- colnames(sample_info)
  sample_factors <-
    sample_factors[!sample_factors %in% c('id', comp_fct)]

  df %>%
    pivot_longer(all_of(sample_info$id), names_to = 'group', values_to = 'value') %>%
    left_join(sample_info, by = c('group' = 'id')) %>%
    rename(comp_fct = {{ comp_fct }}) %>%
    group_by(across(all_of(c(id_col, sample_factors)))) %>%
    pairwise_t_test(
        value ~ comp_fct,
        pool.sd = FALSE,
        var.equal = TRUE
    ) %>%
    group_by(.data[[id_col]]) %>%
    mutate(p.adj = p.adjust(p, method = p_adj_method)) %>%
    select(-p.adj.signif)
}


mdx_anova_filtered <- mdx_anova %>% filter(`genotype:age_days:tissue_fdr` < 0.1) %>% filter(is.na(gene_name) | gene_name != 'Rn7s6')
posthocs_a <- compute_posthoc(
  mdx_anova_filtered,
  id_col = 'gene_stable_id',
  comp_fct = 'age_days',
  sample_info = sample_info %>% select(-mouse_id)
)
posthocs_g <- compute_posthoc(
  mdx_anova_filtered,
  id_col = 'gene_stable_id',
  comp_fct = 'genotype',
  sample_info = sample_info %>% select(-mouse_id)
)

bind_rows(
  posthocs_a, posthocs_g
) %>%
group_by(gene_stable_id) %>%
mutate(p.adj = p.adjust(p, method = 'bonferroni')) %>%
left_join(select(mdx_anova, gene_stable_id, gene_name)) %>%
relocate(age_days_fct, .after = age_days_fct) %>%
relocate(gene_name, .after = gene_stable_id) %>%
unite('group', genotype_fct, age_days_fct, tissue_fct, na.rm = TRUE) %>%
unite('comparison', group1, group2, sep = ' vs ') %>%
select(-c(.y., n1, n2, statistic, df)) %>%


arrange(gene_stable_id) -> a

folds_a <- compute_folds(
  mdx_anova_filtered,
  'gene_stable_id',
  sample_info,
  c(
    'mdx_10_cerebellum - wt_10_cerebellum',
    'mdx_70_cerebellum - wt_70_cerebellum',
    'mdx_10_cerebrum - wt_10_cerebrum',
    'mdx_70_cerebrum - wt_70_cerebrum',

    'wt_70_cerebellum - wt_10_cerebellum',
    'mdx_70_cerebellum - mdx_10_cerebellum',
    'wt_70_cerebrum - wt_10_cerebrum',
    'mdx_70_cerebrum - mdx_10_cerebrum'
  )
) %>%
select(gene_stable_id, contains(' - ')) %>%
mutate(
  `10_cerebellum` = `mdx_10_cerebellum - wt_10_cerebellum`,
  `10_cerebrum` = `mdx_10_cerebrum - wt_10_cerebrum`,
  `70_cerebellum` = `mdx_70_cerebellum - wt_70_cerebellum`,
  `70_cerebrum` = `mdx_70_cerebrum - wt_70_cerebrum`,

  `fold 10_cerebellum` = abs(`10_cerebellum`),
  `dir 10_cerebellum wt vs mdx` = if_else(`10_cerebellum` > 0, 'up', 'down'),
  `fold 10_cerebrum` = abs(`10_cerebrum`),
  `dir 10_cerebrum wt vs mdx` = if_else(`10_cerebrum` > 0, 'up', 'down'),
  `fold 70_cerebellum` = abs(`70_cerebellum`),
  `dir 70_cerebellum wt vs mdx` = if_else(`70_cerebellum` > 0, 'up', 'down'),
  `fold 70_cerebrum` = abs(`70_cerebrum`),
  `dir 70_cerebrum wt vs mdx` = if_else(`70_cerebrum` > 0, 'up', 'down'),


  `wt_cerebellum` = `wt_70_cerebellum - wt_10_cerebellum`,
  `wt_cerebrum` = `wt_70_cerebrum - wt_10_cerebrum`,
  `mdx_cerebellum` = `mdx_70_cerebellum - mdx_10_cerebellum`,
  `mdx_cerebrum` = `mdx_70_cerebrum - mdx_10_cerebrum`,

  `fold wt_cerebellum` = abs(`wt_cerebellum`),
  `dir wt_cerebellum 10days vs 10weeks` = if_else(`wt_cerebellum` > 0, 'up', 'down'),
  `fold wt_cerebrum` = abs(`wt_cerebrum`),
  `dir wt_cerebrum 10days vs 10weeks` = if_else(`wt_cerebrum` > 0, 'up', 'down'),
  `fold mdx_cerebellum` = abs(`mdx_cerebellum`),
  `dir mdx_cerebellum 10days vs 10weeks` = if_else(`mdx_cerebellum` > 0, 'up', 'down'),
  `fold mdx_cerebrum` = abs(`mdx_cerebrum`),
  `dir mdx_cerebrum 10days vs 10weeks` = if_else(`mdx_cerebrum` > 0, 'up', 'down'),

  .keep = 'unused'
) %>%
  select(-c(`10_cerebellum`, `10_cerebrum`, `70_cerebellum`, `70_cerebrum`,
    `mdx_cerebellum`, `mdx_cerebrum`, `wt_cerebellum`, `wt_cerebrum`))

a %>%
  arrange(group) %>%
  unite('name', comparison, group, sep = ' in ') %>%
  rename(p_bf = p.adj) %>%
  pivot_wider(names_from = name, values_from = c(p, p_bf), names_glue = '{name} {.value}') %>%
  left_join(folds_a) %>%

write_csv('interaction_genes_posthoc.csv')


# posthocs <- read_rds(posthoc_rds_path)
```

```{r}
folds <- compute_folds(
  mdx_anova_filtered,
  'gene_stable_id',
  sample_info,
  c(
    'mdx_10_cerebellum - wt_10_cerebellum',
    'mdx_70_cerebellum - wt_70_cerebellum',
    'mdx_10_cerebrum - wt_10_cerebrum',
    'mdx_70_cerebrum - wt_70_cerebrum'
  )
)
```

```{r}
posthocs_right <-
  posthocs %>%
  ungroup() %>%
  select(-.y.:-df, -p) %>%
  pivot_wider(names_from = rev(ends_with('_fct')), values_from = p.adj) %>%
  rename_with(function(x) paste0('posthoc_', x, 'days_pvalue'), -gene_stable_id)
folds_left <-
  folds %>%
  select(-mdx_10_cerebellum:-wt_70_cerebrum) %>%
  pivot_longer(-gene_stable_id, values_to = "fold") %>%
  mutate(
    dir = if_else(sign(fold) == -1, "down", "up"),
    fold = abs(fold)
  ) %>%
  mutate(
    age_days_fct = as.integer(str_match(name, '\\d{2}')),
    tissue_fct = as.character(str_match(name, '[a-z]*$')),
    .keep = 'unused'
  ) %>%
  pivot_wider(
    names_from = ends_with('_fct'),
    values_from = c(fold, dir),
    names_glue = '{tissue_fct}_{age_days_fct}days_{.value}'
  ) %>%
  rename_with(function(x) paste0('posthoc_', x), -gene_stable_id)

mdx_anova %>%
  rename_with(function(x) paste0('anova_', x), ends_with('_fdr')) %>%
  select(gene_stable_id, gene_name, ends_with('_fdr')) %>%
  right_join(posthocs_left, by = 'gene_stable_id') %>%
  left_join(folds_right, by = 'gene_stable_id') %>%
  select(
    gene_stable_id, gene_name,
    ends_with('_fdr'),
   contains('cerebellum_10'),
   contains('cerebrum_10'),
   contains('cerebellum_70'),
   contains('cerebrum_70')
  ) %>%
  write_csv('results/posthoc_genotype.csv')
```


```{r draw_heatmaps, echo=FALSE, fig.align="center", fig.height=16, fig.width=13, results='asis', include=TRUE, warning=FALSE}
fold_th <- 1.3
p_th <- 0.05/4
  plot_data <-
    a %>%
    pivot_wider(id_col = gene_name, names_from = ends_with('_fct'), values_from = p) %>%
    left_join(mdx_anova, by = 'gene_name') %>%
    left_join(b, by = 'gene_stable_id') %>%
    # filter(
    #    `10_cerebellum` < p_th
    #   |  `10_cerebrum` < p_th
    #   |  `10_cerebellum` < p_th
    #   |  `70_cerebrum` < p_th
    # )
    filter(
      abs(`mdx_10_cerebellum - wt_10_cerebellum`) > fold_th & `10_cerebellum` < p_th
      | abs(`mdx_10_cerebrum - wt_10_cerebrum`) > fold_th & `10_cerebrum` < p_th
      | abs(`mdx_70_cerebellum - wt_70_cerebellum`) > fold_th & `10_cerebellum` < p_th
      | abs(`mdx_70_cerebrum - wt_70_cerebrum`) > fold_th & `70_cerebrum` < p_th
    )

  .x <- plot_data %>% select(contains('sample')) %>% as.matrix()
  .rdbu_ramp <- colorRampPalette(brewer.pal(11, "RdBu"))
  .col_side_colors <- as.matrix(tibble(
      '10 days / 70 days' = rep(c(rep('green', 5), rep('magenta', 5)), 4),
      'wt / mdx' = rep(c(rep('yellow', 10), rep('black', 10)), 2),
      'cerebrum / cerebellum' = c(rep('red', 20), rep('blue', 20)),
  ))
  way <- 'way'
  th <- '0000'
  print(paste(way, ' FDR < ', th, collapse = ''))
  h <- heatmap.3(
      x = .x,
      main = paste(way, ' FDR < ', th, collapse = ''),
      Rowv = TRUE,
      Colv = FALSE,
      dendrogram = 'row',
      distfun = function(x) as.dist(1-cor(t(x))),
      scale = "row",
      breaks = seq(-3.5, 3.5, length.out = 25),
      col = rev(.rdbu_ramp(24)),
      trace = "none",
      ColSideColors = .col_side_colors,
      ColSideColorsSize = 8,
      key = FALSE,
      lhei = c(1.5, 20),
      labRow = pull(plot_data, gene_name),
      cexRow = 1.2,
      cexCol = 1.5,
      # offsetRow = 0,
  )
```
