---
title: "portsmouth-darek-mdxbrain"
output:
  html_document:
    toc: yes
    df_print: paged

date: "_Last draft: `r format(Sys.time(), '%d %B, %Y %H:%M:%S')`_"
description: "mdx mice analysis"

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', format(Sys.time(), "%Y-%m-%d_%H-%M"), '.html'
      ),
      knit_root_dir = xfun::proj_root(),
      envir = globalenv()
    )
  })
---


```{r load_libraries, include=FALSE}
library(tidyverse)
library(preprocessCore)
library(future.apply)
library(rstatix)
library(RColorBrewer)
library(tictoc)
library(sva)
library(knitr)

source('analysis/utils.R')
anova_rds_path <- 'data/mdx_3way_anova.RDS'
anova_rds_path <- 'data/mdx_3way_anova_remove_factors_within_tissue.RDS'
anova_rds_path <- 'data/mdx_3way_anova_remove_factors_between_tissue.RDS'
anova_rds_path <- 'data/mdx_3way_anova_all_factors_within_tissue.RDS'
anova_rds_path <- 'data/mdx_3way_anova_all_factors_between_tissue.RDS'
sample_info_rds_path <- 'data/sample_info.RDS'

aux_cols <- c('gene_description', 'chr', 'gene_synonym', 'gene_type')
```

```{r read_anova_results}
mdx_anova <- readRDS(anova_rds_path)
sample_info <- readRDS(sample_info_rds_path)

plot_info <-
  sample_info %>%
  arrange(desc(genotype), desc(tissue), age_days) %>%
  mutate(
    `10 days / 70 days` = if_else(age_days == 10, 'green', 'magenta'),
    `cerebrum / cerebellum` = if_else(tissue == 'cerebrum', 'red', 'blue'),
    `wt / mdx` = if_else(genotype == 'wt', 'yellow', 'black'),
  )
```

```{r compute_folds}
get_sample_names <- function(sample_info, genotype, age_days, tissue) {
  stopifnot(genotype %in% c('wt', 'mdx'))
  stopifnot(age_days %in% c(10, 70))
  stopifnot(tissue %in% c('cerebrum', 'cerebellum'))
  genotype_ = genotype
  age_days_ = age_days
  tissue_ = tissue

  sample_info %>%
    filter(
      genotype == genotype_,
      age_days == age_days_,
      tissue == tissue_
    ) %>%
    pull(id)
}

mdx_anova_folds <-
  mdx_anova %>%
  mutate(
    wt_10_cerebrum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'wt', 10, 'cerebrum')
    ),
    wt_10_cerebellum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'wt', 10, 'cerebellum')
    ),
    wt_70_cerebrum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'wt', 70, 'cerebrum')
    ),
    wt_70_cerebellum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'wt', 70, 'cerebellum')
    ),
    mdx_10_cerebrum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'mdx', 10, 'cerebrum')
    ),
    mdx_10_cerebellum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'mdx', 10, 'cerebellum')
    ),
    mdx_70_cerebrum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'mdx', 70, 'cerebrum')
    ),
    mdx_70_cerebellum_mean = apply(
      select(., matches('sample_[MB][DW][1-5]C?')),
      1,
      function(x, names) {mean(x[names])},
      names = get_sample_names(sample_info, 'mdx', 70, 'cerebellum')
    ),
  ) %>%
  mutate(
    fold_10_cerebrum = wt_10_cerebrum_mean - mdx_10_cerebrum_mean,
    regulation_10_cerebrum = if_else(fold_10_cerebrum < 0, 'up', 'down'),

    fold_10_cerebellum = wt_10_cerebellum_mean - mdx_10_cerebellum_mean,
    regulation_10_cerebellum = if_else(fold_10_cerebellum < 0, 'up', 'down'),

    fold_70_cerebrum = wt_70_cerebrum_mean - mdx_70_cerebrum_mean,
    regulation_70_cerebrum = if_else(fold_70_cerebrum < 0, 'up', 'down'),

    fold_70_cerebellum = wt_70_cerebellum_mean - mdx_70_cerebellum_mean,
    regulation_70_cerebellum = if_else(fold_70_cerebellum < 0, 'up', 'down'),
  ) %>%
  mutate(
    fold_10_cerebrum = abs(fold_10_cerebrum),
    fold_10_cerebellum = abs(fold_10_cerebellum),
    fold_70_cerebrum = abs(fold_70_cerebrum),
    fold_70_cerebellum = abs(fold_70_cerebellum),
  )
```

```{r heatmap_data}
fold_th <- 1.3
k_clusters <- 4

heatmap_data <-
  mdx_anova_folds %>%
  filter(
    pmax(
      fold_10_cerebrum,
      fold_10_cerebellum,
      fold_70_cerebrum,
      fold_70_cerebellum
    ) > fold_th
  ) %>%
  mutate(
    fdr_005 = pmin(
      `genotype_fdr`,
      `genotype:age_days_fdr`,
      `genotype:tissue_fdr`,
      `genotype:age_days:tissue_fdr`
    ) < 0.05,
    .after = gene_name
  )
```


```{r draw_heatmap_03, echo=FALSE, fig.align="center", fig.height=14, fig.width=10, results='asis', include=TRUE, warning=FALSE}
fdr_th <- 0.3
plot_data <-
  heatmap_data %>%
  filter(
    pmin(
      `genotype_fdr`,
      `genotype:age_days_fdr`,
      `genotype:tissue_fdr`,
      `genotype:age_days:tissue_fdr`
    ) < fdr_th
  )

.x <- plot_data %>% select(all_of(plot_info$id)) %>% as.matrix()
rownames(.x) <- plot_data$gene_name
.rdbu_ramp <- colorRampPalette(brewer.pal(11, "RdBu"))
.col_side_colors <- plot_info %>% select(contains('/')) %>% as.matrix()
.way = 'genotype / genotype:tissue / genotype:age_days / genotype:tissue:age_days'

# png('results/genotype-03.png', width = 1000*1.5, height = 1600*1.5, pointsize = 19)
h <- heatmap.3(
    x = .x,
    main = paste(.way, ' FDR < ', fdr_th, collapse = ''),
    Rowv = TRUE,
    Colv = FALSE,
    dendrogram = 'row',
    distfun = function(x) as.dist(1-cor(t(x))),
    scale = "row",
    breaks = seq(-2.5, 2.5, length.out = 25),
    col = rev(.rdbu_ramp(24)),
    trace = "none",
    ColSideColors = .col_side_colors,
    ColSideColorsSize = 5,
    key = FALSE,
    lhei = c(1.5, 30),
    lwid = c(1,5),
    cexRow = 1.2,
    cexCol = 1.5,
    margins = c(9, 8),
)
# dev.off()

ct <- cutree(as.hclust(h$rowDendrogram), k = k_clusters)
mdx_anova_clusters <-
  plot_data %>%
  mutate(cluster_03 = ct, .after = gene_name) %>%
  `[`(rev(h$rowInd), TRUE)
```

```{r save_clusters, eval=FALSE}
mdx_anova_clusters %>%
  select(
    -all_of(aux_cols),
    -n_outliers,
    -genotype:-`genotype:age_days:tissue`,
    -starts_with('sample_')
  ) %>%
  write_csv2('results/genotype-fdr03-clusters.csv')
```

```{r gene_count_in_clusters}
gene_count_005 <-
  mdx_anova_clusters %>%
  filter(fdr_005) %>%
  pivot_longer(starts_with('regulation'), names_to = 'regulation_in') %>%
  group_by(cluster_03, regulation_in, value) %>%
  summarise(n_005 = n(), .groups = 'drop')

gene_count_03 <-
  mdx_anova_clusters %>%
  pivot_longer(starts_with('regulation'), names_to = 'regulation_in') %>%
  group_by(cluster_03, regulation_in, value) %>%
  summarise(n_03 = n(), .groups = 'drop')

.missing_rows <- tibble(
  'cluster_03' = c(4, 4),
  'regulation_in' = c('regulation_10_cerebrum', 'regulation_70_cerebrum'),
  'value' = c('up', 'up')
)

gene_count_03 %>%
  full_join(gene_count_005, by = c("cluster_03", "regulation_in", "value")) %>%
  full_join(.missing_rows) %>%
  replace_na(list('n_005' = 0, 'n_03' = 0)) %>%
  arrange(cluster_03, regulation_in, desc(value))
```


```{r draw_heatmap_005, echo=FALSE, fig.align="center", fig.height=10, fig.width=10, results='asis', include=TRUE, warning=FALSE}
plot_data_005 <-
  mdx_anova_clusters %>%
  filter(fdr_005) %>%
  mutate(
    pref = paste(
      if_else(`genotype_fdr` < fdr_th, 'G', '-'),
      if_else(`genotype:age_days_fdr` < fdr_th, 'A', '-'),
      if_else(`genotype:tissue_fdr` < fdr_th, 'T', '-'),
      if_else(`genotype:age_days:tissue_fdr` < fdr_th, 'GAT', '  -  '),
      if_else(`age_days_fdr` < fdr_th, '|a', '|-')
    ),
    .after = fdr_005
  ) %>%
  arrange(cluster_03, pref)

.x <- plot_data_005 %>% select(all_of(plot_info$id)) %>% as.matrix()
rownames(.x) <- paste(plot_data_005$pref, plot_data_005$gene_name)
.rdbu_ramp <- colorRampPalette(brewer.pal(11, "RdBu"))
.row_sep <- plot_data_005 %>% group_by(cluster_03) %>% summarise(n = n()) %>% mutate(m = cumsum(n)) %>% pull(m) %>% `[`(1:k_clusters-1)
.col_sep <- 1:7 * 5
.col_side_colors <- plot_info %>% select(contains('/')) %>% as.matrix()
brewer_colors <- brewer.pal(k_clusters, 'Set1')
.row_side_colors <- plot_data_005 %>% transmute(cluster = brewer_colors[cluster_03]) %>% as.matrix() %>% t()
way = 'genotype / genotype:tissue / genotype:age_days / genotype:tissue:age_days'

png('results/genotype-005-all-factors-within-tissue.png', width = 2000, height = 1800, pointsize = 24)
par(cex.axis=1.6)
h <- heatmap.3(
    x = .x,
    main = paste(way, ' FDR < 0.05', collapse = ''),
    Rowv = FALSE,
    Colv = FALSE,
    breaks = seq(-2.5, 2.5, length.out = 25),
    distfun = function(x) as.dist(1-cor(t(x))),
    scale = "row",
    col = rev(.rdbu_ramp(24)),
    trace = "none",
    ColSideColors = .col_side_colors,
    ColSideColorsSize = 8,
    RowSideColors = .row_side_colors,
    rowsep = .row_sep,
    colsep = .col_sep,
    key = FALSE,
    lhei = c(1.5, 20),
    lwid = c(1,5),
    cexRow = 1.5,
    cexCol = 1.5,
    margins = c(9, 13)
)
dev.off()
```

```{r draw_heatmap_005_means, echo=FALSE, fig.align="center", fig.height=11, fig.width=5, results='asis', include=TRUE, warning=FALSE}
.x <-
  plot_data_005 %>%
  select(ends_with('mean')) %>%
  select(
    wt_10_cerebrum_mean,
    mdx_10_cerebrum_mean,
    wt_70_cerebrum_mean,
    mdx_70_cerebrum_mean,
    wt_10_cerebellum_mean,
    mdx_10_cerebellum_mean,
    wt_70_cerebellum_mean,
    mdx_70_cerebellum_mean
  ) %>%
  as.matrix()
rownames(.x) <- plot_data_005$gene_name
.rdbu_ramp <- colorRampPalette(brewer.pal(11, "RdBu"))
.row_sep <- plot_data_005 %>% group_by(cluster_03) %>% summarise(n = n()) %>% mutate(m = cumsum(n)) %>% pull(m) %>% `[`(1:k_clusters-1)
.col_sep <- 4
.col_side_colors <- plot_info %>% group_by(genotype, age_days, tissue) %>% slice(1) %>% ungroup() %>% select(contains('/')) %>% as.matrix()
.row_side_colors <- plot_data_005 %>% transmute(cluster = brewer_colors[cluster_03]) %>% as.matrix() %>% t()
way = 'g / g:t / g:a / g:t:a'

# png('results/genotype-005-2.png', width = 2000, height = 2000, pointsize = 24)
par(cex.axis=1.6)
h <- heatmap.3(
    x = .x,
    main = paste(way, ' FDR < 0.05', collapse = ''),
    Rowv = FALSE,
    Colv = FALSE,
    breaks = seq(-2.5, 2.5, length.out = 25),
    distfun = function(x) as.dist(1-cor(t(x))),
    scale = "row",
    col = rev(.rdbu_ramp(24)),
    trace = "none",
    ColSideColors = .col_side_colors,
    ColSideColorsSize = 8,
    RowSideColors = .row_side_colors,
    RowSideColorsSize = 2,
    rowsep = .row_sep,
    colsep = .col_sep,
    key = FALSE,
    lhei = c(1.5, 20),
    lwid = c(4,5),
    cexRow = 1.5,
    cexCol = 1.5,
    margins = c(15, 8)
)
# dev.off()
```


### Post-hoc analysis

```{r compute_post_hoc}
if (Sys.info()['sysname'] == 'Windows') {
  plan(multisession)
} else {
  plan(multicore)
}

compute_ttest_genotype <- function(x, template) {
  template %>%
  left_join(as_tibble(x, rownames = 'id'), by = 'id') %>%
  group_by(age_days, tissue) %>%
  pairwise_t_test(
      value ~ genotype,
      pool.sd = FALSE,
      var.equal = TRUE
  ) %>%
  select(age_days, tissue, p)
}
compute_ttest_age_days <- function(x, template) {
  template %>%
  left_join(as_tibble(x, rownames = 'id'), by = 'id') %>%
  group_by(genotype, tissue) %>%
  pairwise_t_test(
      value ~ age_days,
      pool.sd = FALSE,
      var.equal = TRUE
  ) %>%
  select(genotype, tissue, p)
}

ph_data <- as.data.frame(mdx_anova_clusters)
rownames(ph_data) <- ph_data$gene_stable_id

ttest_genotype_bonf <-
  future_apply(
    ph_data %>% select(contains('sample')),
    1,
    compute_ttest_genotype,
    template = sample_info
  ) %>%
  bind_rows(.id = 'gene_stable_id')

ttest_age_days_bonf <-
  future_apply(
    ph_data %>% select(contains('sample')),
    1,
    compute_ttest_age_days,
    template = sample_info
  ) %>%
  bind_rows(.id = 'gene_stable_id')

ttest_bonf <-
  ttest_genotype_bonf %>%
  bind_rows(ttest_age_days_bonf) %>%
  group_by(gene_stable_id) %>%
  mutate(p_bf = p.adjust(p, 'bonferroni')) %>%
  ungroup()
```


```{r save_results}
ttest_bonf_wider <-
  ttest_bonf %>%
  pivot_wider(names_from = c(genotype, age_days, tissue), values_from = c(p, p_bf)) %>%
  rename(
    `wt vs mdx posthoc in 10_cerebellum (p)` = p_NA_10_cerebellum,
    `wt vs mdx posthoc in 10_cerebrum (p)` = p_NA_10_cerebrum,
    `wt vs mdx posthoc in 70_cerebellum (p)` = p_NA_70_cerebellum,
    `wt vs mdx posthoc in 70_cerebrum (p)` = p_NA_70_cerebrum,
    `10 vs 70 posthoc in mdx_cerebellum (p)` = p_mdx_NA_cerebellum,
    `10 vs 70 posthoc in mdx_cerebrum (p)` = p_mdx_NA_cerebrum,
    `10 vs 70 posthoc in wt_cerebellum (p)` = p_wt_NA_cerebellum,
    `10 vs 70 posthoc in wt_cerebrum (p)` = p_wt_NA_cerebrum,
    `wt vs mdx posthoc in 10_cerebellum (bonf)` = p_bf_NA_10_cerebellum,
    `wt vs mdx posthoc in 10_cerebrum (bonf)` = p_bf_NA_10_cerebrum,
    `wt vs mdx posthoc in 70_cerebellum (bonf)` = p_bf_NA_70_cerebellum,
    `wt vs mdx posthoc in 70_cerebrum (bonf)` = p_bf_NA_70_cerebrum,
    `10 vs 70 posthoc in mdx_cerebellum (bonf)` = p_bf_mdx_NA_cerebellum,
    `10 vs 70 posthoc in mdx_cerebrum (bonf)` = p_bf_mdx_NA_cerebrum,
    `10 vs 70 posthoc in wt_cerebellum (bonf)` = p_bf_wt_NA_cerebellum,
    `10 vs 70 posthoc in wt_cerebrum (bonf)` = p_bf_wt_NA_cerebrum,
  )

mdx_anova_clusters %>%
  select(
    -all_of(aux_cols),
    -n_outliers,
    -genotype:-`genotype:age_days:tissue`,
    -starts_with('sample_'),
  ) %>%
  rename(
    `genotype_fdr (anova)` = `genotype_fdr`,
    `age_days_fdr (anova)` = `age_days_fdr`,
    `tissue_fdr (anova)` = `tissue_fdr`,
    `genotype:age_days_fdr (anova)` = `genotype:age_days_fdr`,
    `genotype:tissue_fdr (anova)` = `genotype:tissue_fdr`,
    `age_days:tissue_fdr (anova)` = `age_days:tissue_fdr`,
    `genotype:age_days:tissue_fdr (anova)` = `genotype:age_days:tissue_fdr`,

    `wt vs mdx fold in 10_cerebrum` = fold_10_cerebrum,
    `wt vs mdx fold in 10_cerebellum` = fold_10_cerebellum,
    `wt vs mdx fold in 70_cerebrum` = fold_70_cerebrum,
    `wt vs mdx fold in 70_cerebellum` = fold_70_cerebellum,
    `wt vs mdx regulation in 10_cerebrum` = regulation_10_cerebrum,
    `wt vs mdx regulation in 10_cerebellum` = regulation_10_cerebellum,
    `wt vs mdx regulation in 70_cerebrum` = regulation_70_cerebrum,
    `wt vs mdx regulation in 70_cerebellum` = regulation_70_cerebellum,
  ) %>%
  mutate(
    `10 vs 70 fold in mdx_cerebellum` = mdx_10_cerebellum_mean - mdx_70_cerebellum_mean,
    `10 vs 70 regulation in mdx_cerebellum` = if_else(`10 vs 70 fold in mdx_cerebellum` < 0, 'up', 'down'),

    `10 vs 70 fold in mdx_cerebrum` = mdx_10_cerebrum_mean - mdx_70_cerebrum_mean,
    `10 vs 70 regulation in mdx_cerebrum` = if_else(`10 vs 70 fold in mdx_cerebrum` < 0, 'up', 'down'),

    `10 vs 70 fold in wt_cerebellum` = wt_10_cerebellum_mean - wt_70_cerebellum_mean,
    `10 vs 70 regulation in wt_cerebellum` = if_else(`10 vs 70 fold in wt_cerebellum` < 0, 'up', 'down'),

    `10 vs 70 fold in wt_cerebrum` = wt_10_cerebrum_mean - wt_70_cerebrum_mean,
    `10 vs 70 regulation in wt_cerebrum` = if_else(`10 vs 70 fold in wt_cerebrum` < 0, 'up', 'down'),
  ) %>%
  mutate(
    `10 vs 70 fold in mdx_cerebellum` = abs(`10 vs 70 fold in mdx_cerebellum`),
    `10 vs 70 fold in mdx_cerebrum` = abs(`10 vs 70 fold in mdx_cerebrum`),
    `10 vs 70 fold in wt_cerebellum` = abs(`10 vs 70 fold in wt_cerebellum`),
    `10 vs 70 fold in wt_cerebrum` = abs(`10 vs 70 fold in wt_cerebrum`),
  ) %>%
  full_join(ttest_bonf_wider) %>%
  write_csv2('results/genotype-fdr03-full.csv')
```
