---
title: "portsmouth-darek-mdxbrain"
output:
  html_document:
    toc: yes
    df_print: paged

date: "_Last draft: `r format(Sys.time(), '%d %B, %Y %H:%M:%S')`_"
description: "mdx mice analysis"

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', format(Sys.time(), "%Y-%m-%d_%H-%M"), '.html'
      ),
      knit_root_dir = xfun::proj_root(),
      envir = globalenv()
    )
  })
---


```{r install_libraries, eval=FALSE, include=FALSE}
library(devtools)
devtools::install_github("zhangyuqing/sva-devel")
devtools::install_github("yanlinlin82/ggvenn")
deftools::install_github("jokergoo/ComplexHeatmap")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
# https://github.com/Bioconductor/bioconductor_docker/issues/22
BiocManager::install("preprocessCore", configure.args="--disable-threading")
```

```{r load_libraries, include=FALSE}
library(magick)
library(IRanges)
library(sets)
library(preprocessCore)
library(RColorBrewer)
library(ComplexHeatmap)
library(circlize)
library(tidyverse)

source('analysis/utils.R')
library(edgeR)
library(ggvenn)
```

```{r}
expression_dist_matrix <- function(counts_df) {
  counts_df %>%
  select(starts_with('sample_')) %>%
  as.matrix() %>%
  dist(method = 'canberra') %>%
  as.matrix()
}

overlap_ratio_matrix <- function(counts_df){
  query <- IRanges(
    counts_df$start,
    counts_df$end
  )

  overlap_pairs <-
    findOverlaps(query) %>%
    as.data.frame() %>%
    mutate(
      query_start = counts_df$start[queryHits],
      query_end = counts_df$end[queryHits],
      subject_start = counts_df$start[subjectHits],
      subject_end = counts_df$end[subjectHits],
      query_gene_name = counts_df$gene_name[queryHits],
      subject_gene_name = counts_df$gene_name[subjectHits],
      query_chr = counts_df$chr[queryHits],
      subject_chr = counts_df$chr[subjectHits],
    ) %>%
    mutate(
      overlap_width = pmin(query_end, subject_end)
      - pmax(query_start, subject_start),
      shorter_range = pmin(query_end - query_start, subject_end - subject_start),
      longer_range = pmax(query_end - query_start, subject_end - subject_start),
    ) %>%
    mutate(
      ratio = if_else(query_chr == subject_chr, overlap_width / shorter_range, 0)
    )

  overlap_matrix <- matrix(0, nrow = nrow(dist_matrix), ncol = ncol(dist_matrix))
  for (i in 1:nrow(overlap_pairs)) {
    query <- overlap_pairs[i, 'queryHits']
    subject <- overlap_pairs[i, 'subjectHits']
    ratio <- overlap_pairs[i, 'ratio']

    overlap_matrix[query, subject] <- ratio
  }
  overlap_matrix
}


reduce_sets <- function(gene_sets) {
  out <- list(gene_sets[[1]])
  for (x in gene_sets) {
    create_new <- TRUE
    for (iy in 1:length(out)) {
      y <- out[[iy]]
      if (!set_is_empty(set_intersection(x, y))) {
        out[[iy]] <- sort(unique(c(out[[iy]], x)))
        create_new <- FALSE
      }
    }
    if (create_new)
      out[[length(out) + 1]] <- x
  }
  out
}

gene_sets <- function(m) {
  gene_sets <- apply(unname(m), 1, which)
  new_gene_sets <- list()
  for (x in gene_sets) {
    x <- unname(x)
    if (length(x) > 2) {
      new_gene_sets[[length(new_gene_sets) + 1]] <- x
    }
  }

  if (length(new_gene_sets) == 0) {
    return()
  }

  old_gene_sets <- list()
  while(!identical(old_gene_sets, new_gene_sets)) {
    old_gene_sets <- new_gene_sets
    new_gene_sets <- reduce_sets(old_gene_sets)
  }
  new_gene_sets
}

find_go_genes <- function(go_ids, go_db) {
  genes <- list()
  for (go_id in go_ids) {
    go <- str_subset(go_db, go_id)
    stopifnot(length(go) == 1)
    go_genes <- str_split(go, '\t', simplify = TRUE)[1, -2]  # 1 is a name, 2 is empty
    genes[[go_genes[1]]] <- na.omit(go_genes[-1])
  }
  genes
}
```

```{r read_data}
go_biological_process_2021 <- read_lines(
  'data/GO_Biological_Process_2021.txt',
)

counts_cerebrum_raw <-
  read_tsv('raw/cerebrum_gene-level-counts-annotated.tsv') %>%
  rename(
    gene_stable_id = `Gene stable ID`,
    gene_description = `Gene description`,
    chr = `Chromosome/scaffold name`,
    gene_name = `Gene name`,
    gene_type = `Gene type`,
    gene_synonym = `Gene Synonym`
  )
counts_cerebellum_raw <-
  read_tsv('raw/cerebellum_gene-level-counts-annotated.tsv') %>%
  rename(
    gene_stable_id = `Gene stable ID`,
    gene_description = `Gene description`,
    chr = `Chromosome/scaffold name`,
    gene_name = `Gene name`,
    gene_type = `Gene type`,
    gene_synonym = `Gene Synonym`
  )
counts_raw <-
  full_join(
    read_tsv('raw/cerebrum_gene-level-counts-annotated.tsv'),
    read_tsv('raw/cerebellum_gene-level-counts-annotated.tsv'),
    by = c(
      'Gene stable ID', 'Transcript stable ID', 'Exon stable ID',
      'Gene description', 'Chromosome/scaffold name', 'Gene start (bp)',
      'Gene end (bp)', 'Gene name', 'Gene type', 'Gene Synonym'
    )
  ) %>%
  rename(
    gene_stable_id = `Gene stable ID`,
    gene_description = `Gene description`,
    chr = `Chromosome/scaffold name`,
    gene_name = `Gene name`,
    gene_type = `Gene type`,
    gene_synonym = `Gene Synonym`
  )

.sample_pattern <- "(sample_(\\w)(\\w)\\d)(C?)"
sample_info <-
  tibble(id = colnames(counts_raw)) %>%
  mutate(mouse_id = str_match(id, .sample_pattern)[, 2]) %>%
  filter(!is.na(mouse_id)) %>%
  mutate(
    genotype = str_match(id, .sample_pattern)[,3],
    age_days = str_match(id, .sample_pattern)[,4],
    tissue = str_match(id, .sample_pattern)[,5],
  ) %>%
  mutate(
    genotype = if_else(
      genotype == 'B',
      'wt',
      if_else(genotype == 'M', 'mdx', NA)
    ),
    age_days = if_else(
      age_days == 'D',
      10,
      if_else(age_days == 'W', 70, NA)
    ),
    tissue = if_else(
      tissue == 'C',
      'cerebrum',
      if_else(tissue == '', 'cerebellum', NA)
    ),
  )
```

```{r remove_duplicated_genes}
duplicated_genes <- c()

chr_subset <- c('1', '2', '3', '4', '5', '6', '7', '8')
counts_chr <-
  counts_raw %>%
  filter(gene_type == 'protein_coding') %>%
  rename(start=`Gene start (bp)`, end=`Gene end (bp)`) %>%
  select(gene_stable_id, gene_name, chr, start, end, starts_with('sample_')) %>%
  mutate(g = chr %in% chr_subset)

dist_matrix <- expression_dist_matrix(filter(counts_chr, g))
overlap_matrix <- overlap_ratio_matrix(filter(counts_chr, g))
result <- (overlap_matrix > 0.5) & (dist_matrix < 1.0)

for (s in gene_sets(result)) {
  print(s)
  genes <-
    counts_chr %>%
    filter(g) %>%
    slice(s) %>%
    mutate(sum = apply(select(., starts_with('sample_')), 1, sum)) %>%
    arrange(-sum) %>%
    slice(-1) %>%
    pull(gene_stable_id)


    counts_chr %>%
    filter(g) %>%
    slice(s) %>%print

  duplicated_genes <- c(duplicated_genes, genes)
}

dist_matrix <- expression_dist_matrix(filter(counts_chr, !g))
overlap_matrix <- overlap_ratio_matrix(filter(counts_chr, !g))
result <- (overlap_matrix > 0.5) & (dist_matrix < 1)

for (s in gene_sets(result)) {
  print(s)
  genes <-
    counts_chr %>%
    filter(!g) %>%
    slice(s) %>%
    mutate(sum = apply(select(., starts_with('sample_')), 1, sum)) %>%
    arrange(-sum) %>%
    slice(-1) %>%
    pull(gene_stable_id)

    counts_chr %>%
    filter(!g) %>%
    slice(s) %>%print

  duplicated_genes <- c(duplicated_genes, genes)
}

counts_cerebrum_raw <-
  filter(counts_cerebrum_raw, !gene_stable_id %in% duplicated_genes)
counts_cerebellum_raw <-
  filter(counts_cerebellum_raw, !gene_stable_id %in% duplicated_genes)
counts_raw <-
  filter(counts_raw, !gene_stable_id %in% duplicated_genes)
```

```{r prepare_data}
counts_cerebrum_normalized_log <-
  counts_cerebrum_raw %>%
  select(starts_with('sample_')) %>%
  as.matrix() %>%
  normalize.quantiles(keep.names = TRUE) %>%
  {{ log2(. + 1) }}
counts_cerebellum_normalized_log <-
  counts_cerebellum_raw %>%
  select(starts_with('sample_')) %>%
  as.matrix() %>%
  normalize.quantiles(keep.names = TRUE) %>%
  {{ log2(. + 1) }}
counts_normalized_log <-
  counts_raw %>%
  select(starts_with('sample_')) %>%
  as.matrix() %>%
  normalize.quantiles(keep.names = TRUE) %>%
  {{ log2(. + 1) }}

counts <-
  counts_raw %>%
  select(
    gene_stable_id, gene_description, chr, gene_name, gene_type, gene_synonym
  ) %>%
  bind_cols(counts_normalized_log)
counts_cerebrum <-
  counts_raw %>%
  select(
    gene_stable_id, gene_description, chr, gene_name, gene_type, gene_synonym
  ) %>%
  bind_cols(counts_cerebrum_normalized_log)
counts_cerebellum <-
  counts_raw %>%
  select(
    gene_stable_id, gene_description, chr, gene_name, gene_type, gene_synonym
  ) %>%
  bind_cols(counts_cerebellum_normalized_log)
```

```{r}
plot_info <-
  sample_info %>%
  arrange(desc(tissue), age_days, desc(genotype)) %>%
  mutate(
    `wt / mdx` = if_else(genotype == 'wt', 'yellow', 'black'),
    `10 days / 70 days` = if_else(age_days == 10, 'green', 'magenta'),
    `cerebrum / cerebellum` = if_else(tissue == 'cerebrum', 'red', 'blue'),
  )
```

```{r fit_model}
edger_model <- function(x, sample_info_groups, tissue=NA, contrast='genotype'){
  mdx_groups. <-
    sample_info_groups %>%
    `[`(match(colnames(x), .$id), ) %>%
    pull(group) %>%
    factor()

  dge_counts <- DGEList(counts = x, group = mdx_groups.)
  keep_counts <- filterByExpr(dge_counts)
  dge_counts <- dge_counts[keep_counts, , keep.lib.sizes = FALSE]

  dge_counts <- calcNormFactors(dge_counts)
  design <- model.matrix(~ 0 + mdx_groups.)
  dge_counts <- estimateDisp(dge_counts, design)

  fit <- glmQLFit(dge_counts, design)

  # contrasts
  if (tissue %in% c('cerebrum', 'cerebellum')){
    contrasts <- makeContrasts(
      # overall genotype effect
      genotype=(
        (mdx_groups.wt_10 + mdx_groups.wt_70)
        - (mdx_groups.mdx_10 + mdx_groups.mdx_70)
      ),
      genotype_10=mdx_groups.wt_10 - mdx_groups.mdx_10,
      genotype_70=mdx_groups.wt_70 - mdx_groups.mdx_70,
      age_days=(
        (mdx_groups.wt_10 + mdx_groups.mdx_10)
        - (mdx_groups.wt_70 + mdx_groups.mdx_70)
      ),
      interaction=(
        (mdx_groups.wt_10 - mdx_groups.mdx_10)
        - (mdx_groups.wt_70 - mdx_groups.mdx_70)
      ),
      levels = design
    )
  } else {
    contrasts <- makeContrasts(
      # overall genotype effect
      genotype=
        (
          mdx_groups.wt_10_cerebrum + mdx_groups.wt_70_cerebrum
          + mdx_groups.wt_10_cerebellum + mdx_groups.wt_70_cerebellum
        )
        - (
          mdx_groups.mdx_10_cerebrum + mdx_groups.mdx_70_cerebrum
          + mdx_groups.mdx_10_cerebellum + mdx_groups.mdx_70_cerebellum
        ),
      levels = design
    )
  }
  results <- glmQLFTest(fit, contrast=contrasts[, contrast])

  topTags(results, n = 'inf')$table %>%
    as_tibble(rownames = 'row_index')
}
```

```{r edger_statistic}
.cerebrum_edger <- function(contrast) {
  edger_model(
    select(counts_cerebrum_raw, starts_with('sample_')),
    sample_info %>%
      filter(tissue == 'cerebrum') %>%
      mutate(group = paste(genotype, age_days, sep = '_')),
    tissue = 'cerebrum',
    contrast = contrast
  )
}

edger_genes_cerebrum <-
  .cerebrum_edger(
    contrast = 'genotype'
  ) %>%
  rename_with(.fn = ~ paste0(.x, '.genotype'), .cols = -row_index) %>%
  full_join(
    rename_with(
      .cerebrum_edger(contrast = 'genotype_10'),
      .fn = ~ paste0(.x, '.genotype_10'),
      .cols = -row_index
    )
  ) %>%
  full_join(
    rename_with(
      .cerebrum_edger(contrast = 'genotype_70'),
      .fn = ~ paste0(.x, '.genotype_70'),
      .cols = -row_index
    )
  ) %>%
  full_join(
    rename_with(
      .cerebrum_edger(contrast = 'age_days'),
      .fn = ~ paste0(.x, '.age_days'),
      .cols = -row_index
    )
  ) %>%
  full_join(
    rename_with(
      .cerebrum_edger(contrast = 'interaction'),
      .fn = ~ paste0(.x, '.interaction'),
      .cols = -row_index
    )
  ) %>%
  mutate(
    gene_name = counts_cerebrum_raw[as.numeric(.$row_index), ]$gene_name,
    gene_stable_id = counts_cerebrum_raw[as.numeric(.$row_index), ]$gene_stable_id,
    gene_type = counts_cerebrum_raw[as.numeric(.$row_index), ]$gene_type,
    .before = everything()
  ) %>%
  filter(gene_type == 'protein_coding') %>%
  select(-row_index, -gene_type)

.cerebellum_edger <- function(contrast) {
  edger_model(
    select(counts_cerebellum_raw, starts_with('sample_')),
    sample_info %>%
      filter(tissue == 'cerebellum') %>%
      mutate(group = paste(genotype, age_days, sep = '_')),
    tissue = 'cerebellum',
    contrast = contrast
  )
}
edger_genes_cerebellum <-
  .cerebellum_edger(
    contrast = 'genotype'
  ) %>%
  rename_with(.fn = ~ paste0(.x, '.genotype'), .cols = -row_index) %>%
  full_join(
    rename_with(
      .cerebellum_edger(contrast = 'genotype_10'),
      .fn = ~ paste0(.x, '.genotype_10'),
      .cols = -row_index
    )
  ) %>%
  full_join(
    rename_with(
      .cerebellum_edger(contrast = 'genotype_70'),
      .fn = ~ paste0(.x, '.genotype_70'),
      .cols = -row_index
    )
  ) %>%
  full_join(
    rename_with(
      .cerebellum_edger(contrast = 'age_days'),
      .fn = ~ paste0(.x, '.age_days'),
      .cols = -row_index
    )
  ) %>%
  full_join(
    rename_with(
      .cerebellum_edger(contrast = 'interaction'),
      .fn = ~ paste0(.x, '.interaction'),
      .cols = -row_index
    )
  ) %>%
  mutate(
    gene_name = counts_cerebellum_raw[as.numeric(.$row_index), ]$gene_name,
    gene_stable_id = counts_cerebellum_raw[as.numeric(.$row_index), ]$gene_stable_id,
    gene_type = counts_cerebellum_raw[as.numeric(.$row_index), ]$gene_type,
    .before = everything()
  ) %>%
  filter(gene_type == 'protein_coding') %>%
  select(-row_index, -gene_type)

edger_genes_tissues <-
  full_join(
    edger_genes_cerebrum,
    edger_genes_cerebellum,
    suffix = c('.cerebrum', '.cerebellum'),
    by = c('gene_name', 'gene_stable_id')
  )
```

```{r result_util_function}
cluster_stats <- function(z_scores, df, h) {
  ct <- 1
  clusters_df <- tibble()
  for (ct_heatmap_order in row_order(h)) {
    cluster_data <- slice(plot_data, ct_heatmap_order)
    mean_z <- list()
    for (group in list(c('wt 10 days'), c('mdx 10 days'), c('wt 10 weeks'), c('mdx 10 weeks'))) {
      mean_z[[group]] <- mean(z_scores[ct_heatmap_order, colnames(z_scores) == group])
    }

    clusters_df <- bind_rows(
      clusters_df,
      tibble(
        gene_name = cluster_data %>% pull(gene_name),
        cluster = ct,
        genotype_10 = cluster_data %>% pull(FDR.genotype_10) < fdr_th,
        genotype_70 = cluster_data %>% pull(FDR.genotype_70) < fdr_th,
        as_tibble(mean_z)
      )
    )
    ct <- ct + 1
  }

  clusters_df %>%
    group_by(cluster) %>%
    summarise(
      n = n(),
      genotype_10_n = sum(genotype_10),
      genotype_70_n = sum(genotype_70),
      across(matches('days|weeks'), mean)
    )
}
```


# Cerebrum

```{r edger_cerebrum}
tiss = 'cerebrum'

plot_info_cerebrum <-
  plot_info %>%
  filter(tissue == tiss) %>%
  mutate(
    `cerebrum /` = `cerebrum / cerebellum`,
    .before = `cerebrum / cerebellum`,
    .keep = 'unused'
  )
```

```{r}
edger_genes_cerebrum %>%
  select(-starts_with('F.'), -starts_with('PValue.'), -starts_with('logCPM.')) %>%
  mutate(
    `age regulation` = if_else(logFC.age_days < 0, 'up', 'down'),
    `genotype regulation` = if_else(logFC.genotype < 0, 'up', 'down'),
    `genotype 10 days regulation` = if_else(logFC.genotype_10 < 0, 'up', 'down'),
    `genotype 10 weeks regulation` = if_else(logFC.genotype_70 < 0, 'up', 'down'),
  ) %>%
  mutate(
    across(starts_with('logFC'), .fns = function(x) { x * -1 }),  # contrasts should be negated
  ) %>%
  rename(
    `fold genotype` = logFC.genotype,
    `genotype FDR` = FDR.genotype,
    `fold genotype 10 days` = logFC.genotype_10,
    `genotype 10 days FDR` = FDR.genotype_10,
    `fold genotype 10 weeks` = logFC.genotype_70,
    `genotype 10 weeks FDR` = FDR.genotype_70,
    `fold age` = logFC.age_days,
    `age FDR` = FDR.age_days,
    `interaction FDR` = FDR.interaction
  ) %>%
  select(
    gene_name, gene_stable_id,
    matches('genotype($| FDR| regulation)'),
    matches('genotype 10 days'),
    matches('genotype 10 weeks'),
    matches('age'),
    matches('^interaction FDR$'),
  ) %>%
  write_csv('results/complex-heatmap/edger-cerebrum.csv')
```

```{r draw_heatmap_03, echo=FALSE, fig.align="center", fig.height=20, fig.width=12, results='asis', include=TRUE, warning=FALSE}
fdr_th <- 0.1
top_n_genes <- 10L
go_genes <- find_go_genes(
  c(
    'GO:0007268', 'GO:0016052',  # https://maayanlab.cloud/Enrichr/enrich?dataset=50e71ca36d7625f53d07be601ea0169a
    'GO:0006397', 'GO:0000398',  # https://maayanlab.cloud/Enrichr/enrich?dataset=dfe0a9232ad83c9744642dd342f14e44
    'GO:0048699', 'GO:0007409',  # https://maayanlab.cloud/Enrichr/enrich?dataset=2ad79e0f126153f1168f618974f90a59
    'GO:0006614', 'GO:0045047'  # https://maayanlab.cloud/Enrichr/enrich?dataset=efe1a8dd2c78b99d26e041c785ba8977
  ),
  go_db = go_biological_process_2021
)

plot_data <-
  counts_cerebrum %>%
  full_join(edger_genes_cerebrum, by = c('gene_stable_id', 'gene_name')) %>%
  filter(FDR.genotype < fdr_th) %>%
  filter(gene_stable_id != 'ENSMUSG00000064351') %>%  # after  quantile normalization it's top in all samples (all values are the same)
  arrange(FDR.genotype)

anno_data_right <-
  plot_data %>%
  transmute(
    gene_name = gene_name,
    `genotype 10 days` = if_else(FDR.genotype_10 < fdr_th, 'sig', 'ns'),
    `genotype 10 weeks` = if_else(FDR.genotype_70 < fdr_th, 'sig', 'ns'),
  )
for (go_name in names(go_genes)) {
  anno_data_right <- mutate(
      anno_data_right,
      "{ go_name }" := if_else(toupper(gene_name) %in% go_genes[[go_name]], 'sig', 'ns')
    )
}
anno_data_right <- as.data.frame(anno_data_right)

.x <-
  plot_data %>%
  select(any_of(plot_info_cerebrum$id)) %>%
  as.matrix() %>%
  { t(scale(t(.))) }
.hc_cerebrum <-
  .x %>%
  (function(x) { 1 - cor(t(x)) }) %>%  # correlation as distance
  as.dist() %>%
  hclust()
plot_data_genes <-
  plot_data %>%
  mutate(ct = cutree(.hc_cerebrum, k = 4)) %>%
  group_by(ct) %>%
  mutate(n_na_gene_names = cumsum(is.na(gene_name))) %>%
  mutate(
    genotype_rank = if_else(
      is.na(gene_name), top_n_genes + 1L, min_rank(FDR.genotype) - n_na_gene_names
    )
  ) %>%
  ungroup() %>%
  mutate(at = row_number()) %>%
  filter(genotype_rank <= top_n_genes)
rownames(.x) <- plot_data$gene_name
colnames(.x) <-
  tibble(id = colnames(.x)) %>%
  left_join(sample_info, by = 'id') %>%
  mutate(age_days = if_else(age_days == 10, '10 days', '10 weeks')) %>%
  unite('col_names', genotype, age_days, sep = ' ') %>%
  pull(col_names)
.col_fun <- colorRamp2(
  seq(-2.5, 2.5, length.out = 24),
  rev(colorRampPalette(brewer.pal(11, "RdBu"))(24))
)
.right_annot_col <- list(
      'genotype 10 days' = c('sig'='#114355', 'ns'='#ebebeb'),
      'genotype 10 weeks' = c('sig'='#665200', 'ns'='#ebebeb')
)
for (go_name in names(go_genes)) {
  .right_annot_col[[go_name]] <- c('sig'='black', 'ns'='#ebebeb')
}

.path_base <- paste0(
  'results/complex-heatmap/genotype-edger-', tiss, '-fdr-', fdr_th
)
svg(paste0(.path_base, '.svg'), width = 14, height = 20)
h_cerebrum <- Heatmap(
  .x,
  column_title = paste('genotype effect in', tiss, 'FDR <', format(fdr_th, scientific = FALSE)),
  cluster_columns = FALSE,
  cluster_rows = .hc_cerebrum,
  col = .col_fun,
  row_names_side = 'right',
  show_row_names = FALSE,
  row_dend_width = unit(3, 'cm'),
  row_split = 4,
  column_split = rep(1:4, each = 5),
  column_names_rot = 45,
  show_column_names = FALSE,
  width = unit(350, 'points'),
  top_annotation = c(
    columnAnnotation(
      age = as.character(plot_info_cerebrum$age_days),
      genotype = as.character(plot_info_cerebrum$genotype),
      col = list(
        'age' = c('10' = '#FDBF6F', '70' = '#FF7F00'),
        'genotype' = c('wt' = '#CAB2D6', 'mdx' = '#6A3D9A')
      ),
      show_legend = FALSE,
      show_annotation_name = FALSE
    )
  ),
  right_annotation = c(
    rowAnnotation(
      df = anno_data_right %>% select(starts_with('genotype')),
      gap = unit(5, 'points'),
      annotation_name_rot = 45,
      col = .right_annot_col,
      show_legend = FALSE
    ),
    rowAnnotation(
      df = anno_data_right %>% select(contains('GO:')),
      row_names = anno_mark(
        at = plot_data_genes$at,
        labels = plot_data_genes$gene_name,
      ),
      annotation_label = c(
        '', 'synaptic transmission', 'carbohydrate catabolism',
        'mRNA processing', 'mRNA splicing',
        'generation of neurons', 'axonogenesis',
        'membrane protein targeting', 'ER protein targeting'
      ),
      gap = unit(5, 'points'),
      annotation_name_rot = 45,
      col = .right_annot_col,
      show_legend = FALSE
    )
  ),
  heatmap_legend_param = list(
    title = 'heatmap z-score', at = -3:3, legend_height = unit(3, 'cm')
  ),
  use_raster = TRUE,
)
draw(h_cerebrum)
for (i in 1:4) {
  age_lab = ifelse(i %in% 1:2, '10 days', '10 weeks')
  age_col = ifelse(i %in% 1:2, 'black', 'black')
  gen_lab = ifelse(i %in% c(1, 3), 'C57BL/10', 'mdx')
  gen_col = ifelse(i %in% c(1, 3), 'black', 'white')
  decorate_annotation(
    'age',
    {grid.text(label = age_lab, gp = gpar(col = age_col, fontsize = 11))},
    slice = i
  )
  decorate_annotation(
    'genotype',
    {grid.text(label = gen_lab, gp = gpar(col = gen_col, fontsize = 11))},
    slice = i
  )
}
dev.off()  # fig. 2
image_read(paste0(.path_base, '.svg'))  # show heatmap in Viewer pane

h <- draw(h_cerebrum)
cluster_stats(.x, plot_data, h)

plot_data %>%
  select(gene_name, contains('logFC.genotype'), contains('FDR.genotyp')) %>%
  mutate(across(contains('logFC'), `-`)) %>%
  write_csv(paste0(.path_base, '.csv'))
```

```{r}
h_cerebrum <- draw(h_cerebrum)

ct <- 1
clusters_cerebrum <- tibble()
for (ct_heatmap_order in row_order(h_cerebrum)) {
  gene_names <-
    plot_data %>%
    slice(ct_heatmap_order) %>%
    pull(gene_name)
  gen_10 <- plot_data %>% slice(ct_heatmap_order) %>% pull(FDR.genotype_10) < fdr_th
  gen_70 <- plot_data %>% slice(ct_heatmap_order) %>% pull(FDR.genotype_70) < fdr_th
  clusters_cerebrum <- bind_rows(
    clusters_cerebrum,
    tibble(
      gene_name = gene_names, cluster = ct,
      genotype_10 = gen_10, genotype_70 = gen_70
    )
  )
  ct <- ct + 1
}

clusters_cerebrum %>%
  write_csv(paste0(.path_base, '-clusters.csv'))
```

```{r venn}
th <- 0.1

venn_plot_data <-
  edger_genes_cerebrum %>%
  mutate(
    age = FDR.age_days < th,
    genotype = FDR.genotype < th,
    age_regulation = if_else(logFC.age_days < 0, 'up', 'down'),
    genotype_regulation = if_else(logFC.genotype < 0, 'up', 'down'),
  )

.venn_age_name <- venn_plot_data %>%
  filter(age) %>%
  group_by(age_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(age_regulation)) %>%
  mutate(name = paste(age_regulation, n)) %>%
  pull(name) %>%
  { paste0('overall age effect \n', paste0(., collapse = ' \n ')) }
.venn_genotype_name <- venn_plot_data %>%
  filter(genotype) %>%
  group_by(genotype_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(genotype_regulation)) %>%
  mutate(name = paste(genotype_regulation, n)) %>%
  pull(name) %>%
  { paste0('overall genotype effect \n', paste0(., collapse = ' \n ')) }

ggplot() +
  geom_text(
    mapping = aes(x = 0, y = 2.0),
    label = tiss,
    size = 6
  ) +
  geom_venn(
    aes_string(A = 'age', B = 'genotype'),
    data = venn_plot_data,
    fill_color = c('#0073C2FF', '#EFC000FF'),
    set_names = c(.venn_age_name, .venn_genotype_name),
    set_name_size = 5,
    text_size = 5,
    auto_scale = TRUE,
    show_percentage = FALSE,
    show_outside = 'none',
  ) +
  coord_fixed() +
  theme_void()
ggsave(
  paste0('results/complex-heatmap/venn-', tiss, '-', th, '.svg'),
  bg = 'white',
  width = 9,
  height = 6
)
```

```{r venn_10_70}
th <- 0.1

venn_plot_data <-
  edger_genes_cerebrum %>%
  filter(FDR.genotype < th) %>%
  filter(gene_stable_id != 'ENSMUSG00000064351') %>%  # after  quantile normalization it's top in all samples (all values are the same)
  mutate(
    genotype_10 = FDR.genotype_10 < th,
    genotype_70 = FDR.genotype_70 < th,
    genotype_10_regulation = if_else(logFC.genotype_10 < 0, 'up', 'down'),
    genotype_70_regulation = if_else(logFC.genotype_70 < 0, 'up', 'down')
  )

.venn_genotype_10_name <- venn_plot_data %>%
  filter(genotype_10) %>%
  group_by(genotype_10_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(genotype_10_regulation)) %>%
  mutate(name = paste(genotype_10_regulation, n)) %>%
  pull(name) %>%
  { paste0('genotype effect\nat 10 days \n', paste0(., collapse = ' \n ')) }
.venn_genotype_70_name <- venn_plot_data %>%
  filter(genotype_70) %>%
  group_by(genotype_70_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(genotype_70_regulation)) %>%
  mutate(name = paste(genotype_70_regulation, n)) %>%
  pull(name) %>%
  { paste0('genotype effect\nat 10 weeks \n', paste0(., collapse = ' \n ')) }

ggplot() +
  geom_text(
    mapping = aes(x = 0, y = 2.2),
    label = tiss,
    size = 6
  ) +
  geom_venn(
    aes_string(A = 'genotype_10', B = 'genotype_70'),
    data = venn_plot_data,
    fill_color = c('#0073C2FF', '#EFC000FF'),
    set_names = c(.venn_genotype_10_name, .venn_genotype_70_name, 'overall genotype effect'),
    set_name_size = 5,
    text_size = 5,
    auto_scale = TRUE,
    show_percentage = FALSE,
  ) +
  coord_fixed() +
  theme_void()
ggsave(
  paste0('results/complex-heatmap/venn-', tiss, '-in-age-', th, '.svg'),
  bg = 'white',
  width = 9,
  height = 6
)
```



# Cerebellum

```{r edger_cerebellum}
tiss = 'cerebellum'

plot_info_cerebellum <-
  plot_info %>%
  filter(tissue == tiss) %>%
  mutate(
    `/ cerebellum` = `cerebrum / cerebellum`,
    .before = `cerebrum / cerebellum`,
    .keep = 'unused'
  )
```

```{r}
edger_genes_cerebellum %>%
  select(-starts_with('F.'), -starts_with('PValue.'), -starts_with('logCPM.')) %>%
  mutate(
    `age regulation` = if_else(logFC.age_days < 0, 'up', 'down'),
    `genotype regulation` = if_else(logFC.genotype < 0, 'up', 'down'),
    `genotype 10 days regulation` = if_else(logFC.genotype_10 < 0, 'up', 'down'),
    `genotype 10 weeks regulation` = if_else(logFC.genotype_70 < 0, 'up', 'down'),
  ) %>%
  mutate(
    across(starts_with('logFC'), .fns = function(x) { x * -1 }),
  ) %>%
  rename(
    `fold genotype` = logFC.genotype,
    `genotype FDR` = FDR.genotype,
    `fold genotype 10 days` = logFC.genotype_10,
    `genotype 10 days FDR` = FDR.genotype_10,
    `fold genotype 10 weeks` = logFC.genotype_70,
    `genotype 10 weeks FDR` = FDR.genotype_70,
    `fold age` = logFC.age_days,
    `age FDR` = FDR.age_days,
    `interaction FDR` = FDR.interaction
  ) %>%
  select(
    gene_name, gene_stable_id,
    matches('genotype($| FDR| regulation)'),
    matches('genotype 10 days'),
    matches('genotype 10 weeks'),
    matches('age'),
    matches('^interaction FDR$'),
  ) %>%
  write_csv('results/complex-heatmap/edger-cerebellum.csv')
```

```{r draw_heatmap, echo=FALSE, fig.align="center", fig.width=10, fig.height=14, results='asis', include=TRUE, warning=FALSE}
fdr_th <- 0.1
go_genes <- find_go_genes(
  c(
    'GO:1900034',  # https://maayanlab.cloud/Enrichr/enrich?dataset=c775ed219cdea7ad23122f822d15924e
    'GO:0033146',  # https://maayanlab.cloud/Enrichr/enrich?dataset=744e4f18c6894a38767037523d521681
    'GO:0006936'  # https://maayanlab.cloud/Enrichr/enrich?dataset=9080d555d5451496d428446459a94a0a
    # 'GO:2000812', 'GO:0060441'  # https://maayanlab.cloud/Enrichr/enrich?dataset=dad307fc0684fb36a26f1acfd300c201
  ),
  go_db = go_biological_process_2021
)

plot_data <-
  counts_cerebellum %>%
  full_join(edger_genes_cerebellum, by = c('gene_stable_id', 'gene_name')) %>%
  filter(FDR.genotype < fdr_th, !is.na(gene_name)) %>%
  filter(FDR.interaction > fdr_th) %>%
  mutate(
    genotype_10 = if_else(FDR.genotype_10 < fdr_th, 'sig', 'ns'),
    genotype_70 = if_else(FDR.genotype_70 < fdr_th, 'sig', 'ns'),
  ) %>%
  arrange(FDR.genotype)

anno_data_right <-
  plot_data %>%
  transmute(
    gene_name = gene_name,
    `genotype 10 days` = if_else(FDR.genotype_10 < fdr_th, 'sig', 'ns'),
    `genotype 10 weeks` = if_else(FDR.genotype_70 < fdr_th, 'sig', 'ns'),
  )
for (go_name in names(go_genes)) {
  anno_data_right <- mutate(
      anno_data_right,
      "{ go_name }" := if_else(toupper(gene_name) %in% go_genes[[go_name]], 'sig', 'ns')
    )
}
anno_data_right <- as.data.frame(anno_data_right)

.x <-
  plot_data %>%
  select(any_of(plot_info_cerebellum$id)) %>%
  as.matrix() %>%
  { t(scale(t(.))) }
rownames(.x) <- plot_data$gene_name
colnames(.x) <-
  tibble(id = colnames(.x)) %>%
  left_join(sample_info, by = 'id') %>%
  mutate(age_days = if_else(age_days == 10, '10 days', '10 weeks')) %>%
  unite('col_names', genotype, age_days, sep = ' ') %>%
  pull(col_names)
.col_fun <- colorRamp2(
  seq(-2.5, 2.5, length.out = 24),
  rev(colorRampPalette(brewer.pal(11, "RdBu"))(24))
)
.right_annot_col <- list(
      'genotype 10 days' = c('sig'='#15546a', 'ns'='#ebebeb'),
      'genotype 10 weeks' = c('sig'='#806600', 'ns'='#ebebeb')  # little lighter than cerebrum
)
for (go_name in names(go_genes)) {
  .right_annot_col[[go_name]] <- c('sig'='gray20', 'ns'='#ebebeb')
}

.path_base <- paste0(
  'results/complex-heatmap/genotype-edger-', tiss, '-fdr-', fdr_th
)
svg(paste0(.path_base, '.svg'), width = 10, height = 20)
h_cerebellum <- Heatmap(
  .x,
  column_title = paste('genotype effect in', tiss, 'FDR <', format(fdr_th, scientific = FALSE)),
  cluster_columns = FALSE,
  clustering_distance_rows = function(x) as.dist(1-cor(t(x))),
  col = .col_fun,
  row_names_side = 'right',
  row_dend_width = unit(3, 'cm'),
  row_split = 4,
  column_names_rot = 0,
  column_names_centered = TRUE,
  show_column_names = FALSE,
  column_split = rep(1:4, each = 5),
  top_annotation = c(
    columnAnnotation(
      age = as.character(plot_info_cerebellum$age_days),
      genotype = as.character(plot_info_cerebellum$genotype),
      col = list(
        'age' = c('10' = '#FDBF6F', '70' = '#FF7F00'),
        'genotype' = c('wt' = '#CAB2D6', 'mdx' = '#6A3D9A')
      ),
      show_legend = FALSE,
      show_annotation_name = FALSE
    )
  ),
  right_annotation = c(
    rowAnnotation(
      df = select(anno_data_right, -gene_name),
      annotation_label = c(
        'genotype 10 days', 'genotype 10 weeks',
        'response to heat', 'estrogen receptor signaling', 'muscle contraction'
      ),
      gap = unit(5, 'points'),
      annotation_name_rot = 45,
      col = .right_annot_col,
      show_legend = FALSE
    )
  ),
  heatmap_legend_param = list(
    title = 'heatmap z-score', at = -3:3, legend_height = unit(3, 'cm')
  ),
)
draw(h_cerebellum)
for (i in 1:4) {
  age_lab = ifelse(i %in% 1:2, '10 days', '10 weeks')
  age_col = ifelse(i %in% 1:2, 'black', 'black')
  gen_lab = ifelse(i %in% c(1, 3), 'C57BL/10', 'mdx')
  gen_col = ifelse(i %in% c(1, 3), 'black', 'white')
  decorate_annotation(
    'age',
    {grid.text(label = age_lab, gp = gpar(col = age_col, fontsize = 11))},
    slice = i
  )
  decorate_annotation(
    'genotype',
    {grid.text(label = gen_lab, gp = gpar(col = gen_col, fontsize = 11))},
    slice = i
  )
}
dev.off()
image_read(paste0(.path_base, '.svg'))  # show heatmap in Viewer pane

h <- draw(h_cerebellum)
cluster_stats(.x, plot_data, h)

plot_data %>%
  select(gene_name, contains('logFC.genotype'), contains('FDR.genotyp')) %>%
  mutate(across(contains('logFC'), `-`)) %>%
  write_csv(paste0(.path_base, '.csv'))
```

```{r draw_heatmap_interaction, echo=FALSE, fig.align="center", fig.width=10, fig.height=7, results='asis', include=TRUE, warning=FALSE}
fdr_th <- 0.1

plot_data <-
  counts_cerebellum %>%
  full_join(edger_genes_cerebellum, by = c('gene_stable_id', 'gene_name')) %>%
  filter(FDR.interaction < fdr_th, !is.na(gene_name)) %>%
  arrange(FDR.interaction)

.x <-
  plot_data %>%
  select(any_of(plot_info_cerebellum$id)) %>%
  as.matrix() %>%
  { t(scale(t(.))) }
rownames(.x) <- plot_data$gene_name
colnames(.x) <-
  tibble(id = colnames(.x)) %>%
  left_join(sample_info, by = 'id') %>%
  mutate(age_days = if_else(age_days == 10, '10 days', '10 weeks')) %>%
  unite('col_names', genotype, age_days, sep = ' ') %>%
  pull(col_names)
.col_fun <- colorRamp2(
  seq(-2.5, 2.5, length.out = 24),
  rev(colorRampPalette(brewer.pal(11, "RdBu"))(24))
)

.path_base <- paste0(
  'results/complex-heatmap/genotype-edger-', tiss, '-interaction-fdr', fdr_th
)

svg(paste0(.path_base, '.svg'), width = 8, height = 3)
h_cerebellum <- Heatmap(
  .x,
  column_title = paste('interaction effect in', tiss, 'FDR <', format(fdr_th, scientific = FALSE)),
  cluster_columns = FALSE,
  clustering_distance_rows = function(x) as.dist(1-cor(t(x))),
  col = .col_fun,
  row_names_side = 'right',
  row_dend_width = unit(3, 'cm'),
  row_split = 3,
  column_names_rot = 45,
  column_split = rep(1:4, each = 5),
  show_column_names = FALSE,
  top_annotation = c(
    columnAnnotation(
      age = as.character(plot_info_cerebellum$age_days),
      genotype = as.character(plot_info_cerebellum$genotype),
      col = list(
        'age' = c('10' = '#FDBF6F', '70' = '#FF7F00'),
        'genotype' = c('wt' = '#CAB2D6', 'mdx' = '#6A3D9A')
      ),
      show_legend = FALSE,
      show_annotation_name = FALSE
    )
  ),
  heatmap_legend_param = list(
    title = 'heatmap z-score', at = -3:3, legend_height = unit(3, 'cm')
  ),
)
draw(h_cerebellum)
for (i in 1:4) {
  age_lab = ifelse(i %in% 1:2, '10 days', '10 weeks')
  age_col = ifelse(i %in% 1:2, 'black', 'black')
  gen_lab = ifelse(i %in% c(1, 3), 'C57BL/10', 'mdx')
  gen_col = ifelse(i %in% c(1, 3), 'black', 'white')
  decorate_annotation(
    'age',
    {grid.text(label = age_lab, gp = gpar(col = age_col, fontsize = 11))},
    slice = i
  )
  decorate_annotation(
    'genotype',
    {grid.text(label = gen_lab, gp = gpar(col = gen_col, fontsize = 11))},
    slice = i
  )
}
dev.off()  # fig. 6
image_read(paste0(.path_base, '.svg'))  # show heatmap in Viewer pane

h <- draw(h_cerebellum)
cluster_stats(.x, plot_data, h)


plot_data %>%
  select(gene_name, contains('logFC.interaction'), contains('FDR.interaction')) %>%
  mutate(across(contains('logFC'), `-`)) %>%
  write_csv(paste0(.path_base, '.csv'))
```

```{r}
h_cerebellum <- draw(h_cerebellum)

ct <- 1
clusters_cerebellum <- tibble()
for (ct_heatmap_order in row_order(h_cerebellum)) {
  gene_names <-
    plot_data %>%
    slice(ct_heatmap_order) %>%
    pull(gene_name)
  gen_10 <- plot_data %>% slice(ct_heatmap_order) %>% pull(FDR.genotype_10) < fdr_th
  gen_70 <- plot_data %>% slice(ct_heatmap_order) %>% pull(FDR.genotype_70) < fdr_th
  clusters_cerebellum <- bind_rows(
    clusters_cerebellum,
    tibble(
      gene_name = gene_names, cluster = ct,
      genotype_10 = gen_10, genotype_70 = gen_70
    )
  )
  ct <- ct + 1
}

clusters_cerebellum %>%
  write_csv(paste0(.path_base, '-clusters', '.csv'))
```

```{r venn2}
th <- 0.1

venn_plot_data <-
  edger_genes_cerebellum %>%
  mutate(
    age = FDR.age_days < th,
    genotype = FDR.genotype < th,
    age_regulation = if_else(logFC.age_days < 0, 'up', 'down'),
    genotype_regulation = if_else(logFC.genotype < 0, 'up', 'down'),
  )

.venn_age_name <- venn_plot_data %>%
  filter(age) %>%
  group_by(age_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(age_regulation)) %>%
  mutate(name = paste(age_regulation, n)) %>%
  pull(name) %>%
  { paste0('overall age effect\n', paste0(., collapse = ' \n ')) }
.venn_genotype_name <- venn_plot_data %>%
  filter(genotype) %>%
  group_by(genotype_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(genotype_regulation)) %>%
  mutate(name = paste(genotype_regulation, n)) %>%
  pull(name) %>%
  { paste0('overall genotype effect\n', paste0(., collapse = ' \n ')) }

ggplot() +
  geom_text(
    mapping = aes(x = 0, y = 2.0),
    label = tiss,
    size = 6
  ) +
  geom_venn(
    aes_string(A = 'age', B = 'genotype'),
    data = venn_plot_data,
    fill_color = c('#984EA3FF', '#FF7F00FF'),
    set_names = c(.venn_age_name, .venn_genotype_name),
    set_name_size = 5,
    text_size = 5,
    auto_scale = TRUE,
    show_percentage = FALSE,
    show_outside = 'none',
  ) +
  coord_fixed() +
  theme_void()
ggsave(
  paste0('results/complex-heatmap/venn-', tiss, '-', th, '.svg'),
  bg = 'white',
  width = 9,
  height = 6
)
```

```{r venn_10_702}
th <- 0.1

venn_plot_data <-
  edger_genes_cerebellum %>%
  filter(FDR.genotype < th, !is.na(gene_name)) %>%
  filter(FDR.interaction > th) %>%
  mutate(
    genotype_10 = FDR.genotype_10 < th,
    genotype_70 = FDR.genotype_70 < th,
    genotype_10_regulation = if_else(logFC.genotype_10 < 0, 'up', 'down'),
    genotype_70_regulation = if_else(logFC.genotype_70 < 0, 'up', 'down'),
  )

.venn_genotype_10_name <- venn_plot_data %>%
  filter(genotype_10) %>%
  group_by(genotype_10_regulation) %>%
  summarise(n = n()) %>%
  bind_rows(list(genotype_10_regulation = 'up', n = 0)) %>%
  arrange(desc(genotype_10_regulation)) %>%
  mutate(name = paste(genotype_10_regulation, n)) %>%
  pull(name) %>%
  { paste0('genotype effect\nat 10 days \n', paste0(., collapse = ' \n ')) }
.venn_genotype_70_name <- venn_plot_data %>%
  filter(genotype_70) %>%
  group_by(genotype_70_regulation) %>%
  summarise(n = n()) %>%
  arrange(desc(genotype_70_regulation)) %>%
  mutate(name = paste(genotype_70_regulation, n)) %>%
  pull(name) %>%
  { paste0('genotype effect\nat 10 weeks \n', paste0(., collapse = ' \n ')) }

ggplot() +
  geom_text(
    mapping = aes(x = 0, y = 2.2),
    label = tiss,
    size = 6
  ) +
  geom_venn(
    aes_string(A = 'genotype_10', B = 'genotype_70'),
    data = venn_plot_data,
    fill_color = c('#984EA3FF', '#FF7F00FF'),
    set_names = c(.venn_genotype_10_name, .venn_genotype_70_name),
    set_name_size = 5,
    text_size = 5,
    auto_scale = TRUE,
    show_percentage = FALSE,
  ) +
  coord_fixed() +
  theme_void()
ggsave(
  paste0('results/complex-heatmap/venn-', tiss, '-in-age-', th, '.svg'),
  bg = 'white',
  width = 9,
  height = 6
)
```



# Show selected genes

```{r read_selected_genes}
genes_wawa <- read_tsv('raw/gene-list-wawa.csv', show_col_types = FALSE)$Genes
genes_wawa <- setdiff(genes_wawa, c('Dmd', 'Gphn', 'Dag1', 'Tfam', 'Pklr'))  # not interesting in this analysis
stopifnot(genes_wawa %in% counts$gene_name)

fdr_th <- 0.1
```

```{r}
counts_cerebrum %>%
  full_join(edger_genes_cerebrum, by = c('gene_stable_id', 'gene_name')) %>%
  select(-gene_description, -chr, -gene_type) %>%
  filter(gene_name %in% genes_wawa) %>%
  write_csv('results/selected-genes/selected-genes-cerebrum.csv', na = '')

counts_cerebellum %>%
  full_join(edger_genes_cerebellum, by = c('gene_stable_id', 'gene_name')) %>%
  select(-gene_description, -chr, -gene_type) %>%
  filter(gene_name %in% genes_wawa) %>%
  write_csv('results/selected-genes/selected-genes-cerebellum.csv', na = '')
```

## Cerebrum

```{r edger_cerebrum}
tiss = 'cerebrum'

plot_info_cerebrum <-
  plot_info %>%
  filter(tissue == tiss) %>%
  mutate(
    `cerebrum /` = `cerebrum / cerebellum`,
    .before = `cerebrum / cerebellum`,
    .keep = 'unused'
  )

.outlier_gene <- 'mt-Co1'
```

```{r draw_heatmap_selected_cerebrum, echo=FALSE, fig.align="center", fig.height=10, fig.width=12, results='asis', include=TRUE, warning=FALSE}
plot_data <-
  counts_cerebrum %>%
  full_join(edger_genes_cerebrum, by = c('gene_stable_id', 'gene_name')) %>%
  filter(gene_name %in% genes_wawa) %>%
  arrange(FDR.genotype)

anno_data_right <-
  plot_data %>%
  transmute(
    gene_name = gene_name,
    `genotype 10 days` = if_else(
      FDR.genotype_10 < fdr_th & !is.na(FDR.genotype_10), 'sig', 'ns'
    ),
    `genotype 10 weeks` = if_else(
      FDR.genotype_70 < fdr_th & !is.na(FDR.genotype_70), 'sig','ns'
    ),
  )
anno_data_right <- as.data.frame(anno_data_right)

.outlier_gene_raw <- counts_cerebrum_raw %>%
  filter(gene_name == .outlier_gene) %>%
  select(starts_with('sample_'))
plot_data[plot_data$gene_name == .outlier_gene, names(.outlier_gene_raw)] <- .outlier_gene_raw
plot_data$gene_name[plot_data$gene_name == .outlier_gene] <- paste(.outlier_gene, '(RAW COUNTS)')
.x <-
  plot_data %>%
  select(any_of(plot_info_cerebrum$id)) %>%
  as.matrix() %>%
  { t(scale(t(.))) }
.hc_cerebrum <-
  .x %>%
  (function(x) { 1 - cor(t(x)) }) %>%  # correlation as distance
  as.dist() %>%
  hclust()
rownames(.x) <- ifelse(plot_data$gene_name == 'Pklr', 'Pklr *', plot_data$gene_name)
colnames(.x) <-
  tibble(id = colnames(.x)) %>%
  left_join(sample_info, by = 'id') %>%
  mutate(age_days = if_else(age_days == 10, '10 days', '10 weeks')) %>%
  unite('col_names', genotype, age_days, sep = ' ') %>%
  pull(col_names)
.col_fun <- colorRamp2(
  seq(-2.5, 2.5, length.out = 24),
  rev(colorRampPalette(brewer.pal(11, "RdBu"))(24))
)
.right_annot_col <- list(
      'genotype 10 days' = c('sig'='#114355', 'ns'='#ebebeb'),
      'genotype 10 weeks' = c('sig'='#665200', 'ns'='#ebebeb')
)

.path_base <- paste0('results/selected-genes/selected-genes-', tiss)
svg(paste0(.path_base, '.svg'), width = 11, height = 7.3)
h_cerebrum <- Heatmap(
  .x,
  column_title = paste('Heatmap of selected genes in', tiss),
  cluster_columns = FALSE,
  cluster_rows = .hc_cerebrum,
  col = .col_fun,
  row_names_side = 'right',
  show_row_names = TRUE,
  row_dend_width = unit(3, 'cm'),
  row_split = 4,
  column_split = rep(1:4, each = 5),
  column_names_rot = 45,
  show_column_names = FALSE,
  width = unit(350, 'points'),
  top_annotation = c(
    columnAnnotation(
      age = as.character(plot_info_cerebrum$age_days),
      genotype = as.character(plot_info_cerebrum$genotype),
      col = list(
        'age' = c('10' = '#FDBF6F', '70' = '#FF7F00'),
        'genotype' = c('wt' = '#CAB2D6', 'mdx' = '#6A3D9A')
      ),
      show_legend = FALSE,
      show_annotation_name = FALSE
    )
  ),
  right_annotation = c(
    rowAnnotation(
      df = anno_data_right %>% select(starts_with('genotype')),
      gap = unit(5, 'points'),
      annotation_name_rot = 45,
      col = .right_annot_col,
      show_legend = FALSE
    )
  ),
  heatmap_legend_param = list(title = 'heatmap z-score', at = -3:3, legend_height = unit(3, 'cm')),
)
draw(h_cerebrum)
for (i in 1:4) {
  age_lab = ifelse(i %in% 1:2, '10 days', '10 weeks')
  age_col = ifelse(i %in% 1:2, 'black', 'black')
  gen_lab = ifelse(i %in% c(1, 3), 'C57BL/10', 'mdx')
  gen_col = ifelse(i %in% c(1, 3), 'black', 'white')
  decorate_annotation(
    'age',
    {grid.text(label = age_lab, gp = gpar(col = age_col, fontsize = 11))},
    slice = i
  )
  decorate_annotation(
    'genotype',
    {grid.text(label = gen_lab, gp = gpar(col = gen_col, fontsize = 11))},
    slice = i
  )
}
dev.off()  # fig. 4
image_read(paste0(.path_base, '.svg'))  # show heatmap in Viewer pane

h <- draw(h_cerebrum)
cluster_stats(.x, plot_data, h)
```

## Cerebellum

```{r edger_cerebellum}
tiss = 'cerebellum'

plot_info_cerebellum <-
  plot_info %>%
  filter(tissue == tiss) %>%
  mutate(
    `/ cerebellum` = `cerebrum / cerebellum`,
    .before = `cerebrum / cerebellum`,
    .keep = 'unused'
  )
```

```{r draw_heatmap_selected_cerebellum, echo=FALSE, fig.align="center", fig.width=10, fig.height=14, results='asis', include=TRUE, warning=FALSE}
plot_data <-
  counts_cerebellum %>%
  full_join(edger_genes_cerebellum, by = c('gene_stable_id', 'gene_name')) %>%
  filter(gene_name %in% genes_wawa) %>%
  arrange(FDR.genotype)

anno_data_right <-
  plot_data %>%
  transmute(
    gene_name = gene_name,
    `genotype 10 days` = if_else(FDR.genotype_10 < fdr_th & !is.na(FDR.genotype_10), 'sig', 'ns'),
    `genotype 10 weeks` = if_else(FDR.genotype_70 < fdr_th & !is.na(FDR.genotype_70), 'sig', 'ns'),
  )
anno_data_right <- as.data.frame(anno_data_right)

.x <-
  plot_data %>%
  select(any_of(plot_info_cerebellum$id)) %>%
  as.matrix() %>%
  { t(scale(t(.))) }
rownames(.x) <- ifelse(plot_data$gene_name == 'Pklr', 'Pklr *', plot_data$gene_name)
colnames(.x) <-
  tibble(id = colnames(.x)) %>%
  left_join(sample_info, by = 'id') %>%
  mutate(age_days = if_else(age_days == 10, '10 days', '10 weeks')) %>%
  unite('col_names', genotype, age_days, sep = ' ') %>%
  pull(col_names)
.col_fun <- colorRamp2(
  seq(-2.5, 2.5, length.out = 24),
  rev(colorRampPalette(brewer.pal(11, "RdBu"))(24))
)
.right_annot_col <- list(
      'genotype 10 days' = c('sig'='#15546a', 'ns'='#ebebeb'),
      'genotype 10 weeks' = c('sig'='#806600', 'ns'='#ebebeb')  # little lighter than cerebrum
)

.path_base <- paste0('results/selected-genes/selected-genes-', tiss)
svg(paste0(.path_base, '.svg'), width = 11, height = 7.3)
svg('results/selected-genes/selected-genes-cerebellum.svg', width = 9.5, height = 7)
h_cerebellum <- Heatmap(
  .x,
  column_title = paste('Heatmap of selected genes in', tiss),
  cluster_columns = FALSE,
  clustering_distance_rows = function(x) as.dist(1-cor(t(x))),
  col = .col_fun,
  row_names_side = 'right',
  row_dend_width = unit(3, 'cm'),
  row_split = 2,
  column_names_rot = 45,
  show_column_names = FALSE,
  column_split = rep(1:4, each = 5),
  top_annotation = c(
    columnAnnotation(
      age = as.character(plot_info_cerebellum$age_days),
      genotype = as.character(plot_info_cerebellum$genotype),
      col = list(
        'age' = c('10' = '#FDBF6F', '70' = '#FF7F00'),
        'genotype' = c('wt' = '#CAB2D6', 'mdx' = '#6A3D9A')
      ),
      show_legend = FALSE,
      show_annotation_name = FALSE
    )
  ),
  right_annotation = c(
    rowAnnotation(
      df = select(anno_data_right, -gene_name, -contains('GO:')),
      annotation_label = c(
        'genotype 10 days', 'genotype 10 weeks'
      ),
      gap = unit(5, 'points'),
      annotation_name_rot = 45,
      col = .right_annot_col,
      show_legend = FALSE
    )
  ),
  heatmap_legend_param = list(title = 'heatmap z-score', at = -3:3, legend_height = unit(3, 'cm')),
)
draw(h_cerebellum)
for (i in 1:4) {
  age_lab = ifelse(i %in% 1:2, '10 days', '10 weeks')
  age_col = ifelse(i %in% 1:2, 'black', 'black')
  gen_lab = ifelse(i %in% c(1, 3), 'C57BL/10', 'mdx')
  gen_col = ifelse(i %in% c(1, 3), 'black', 'white')
  decorate_annotation(
    'age',
    {grid.text(label = age_lab, gp = gpar(col = age_col, fontsize = 11))},
    slice = i
  )
  decorate_annotation(
    'genotype',
    {grid.text(label = gen_lab, gp = gpar(col = gen_col, fontsize = 11))},
    slice = i
  )
}
dev.off()
image_read(paste0(.path_base, '.svg'))  # show heatmap in Viewer pane

h <- draw(h_cerebellum)
cluster_stats(.x, plot_data, h)
```


Additional analyses

```{r}
read_csv('results/complex-heatmap/edger-cerebellum.csv') %>%
  select(gene_name, gene_stable_id, contains('genotype 10 days')) %>%
  filter(`genotype 10 days FDR` < 0.1) %>%
  write_csv('results/degs/cerebellum-days.csv')
read_csv('results/complex-heatmap/edger-cerebellum.csv') %>%
  select(gene_name, gene_stable_id, contains('genotype 10 weeks')) %>%
  filter(`genotype 10 weeks FDR` < 0.1) %>%
  write_csv('results/degs/cerebellum-weeks.csv')

read_csv('results/complex-heatmap/edger-cerebrum.csv') %>%
  select(gene_name, gene_stable_id, contains('genotype 10 days')) %>%
  filter(`genotype 10 days FDR` < 0.1) %>%
  write_csv('results/degs/cerebrum-days.csv')
read_csv('results/complex-heatmap/edger-cerebrum.csv') %>%
  select(gene_name, gene_stable_id, contains('genotype 10 weeks')) %>%
  filter(`genotype 10 weeks FDR` < 0.1) %>%
  write_csv('results/degs/cerebrum-weeks.csv')
```
